### ISSUE TITLE
Need maintenance help?

### ISSUE THREAD

**Issue by parasyte** [dtcristo/bevy_pixels#2]
Hi! :wave: `pixels` author here.

I noticed this crate uses a very outdated version of the crate. I am interested in pulling this project into the `pixels` repo so that it stays up-to-date!

@dtcristo If you don't mind transferring the crate name over to me on crates.io, I would be happy to take over.

**Comment by dtcristo** [comment]
Hi @parasyte, I'm well aware it's on an older version of pixels.

Last time I tried upgrading, the new versions were incompatible with the current stable release of bevy (0.5). I couldn't get it building as this version of bevy relies on an older version of wgpu.

When bevy 0.6 is released I will update this library to the latest compatible version of pixels (hopefully the latest).

I'm still keen to maintain this library, but if you want to take over, I'd be okay with that. Happy to hand over the crate name.

**Comment by parasyte** [comment]
Ok, I wasn't aware you had attempted an upgrade. Also I was under the impression that `bevy_pixels` was a drop-in replacement for `bevy_wgpu` and `bevy_render`. Those are the only crates that use `wgpu`, and neither are necessary when using `pixels`.

Anyway, since you wish to continue maintaining the library, I'll leave it in your hands! I might submit a PR though. :)
