### ISSUE TITLE
Example of bevy_pixels power with pixel collision

### ISSUE THREAD

**Issue by pyweeker** [dtcristo/bevy_pixels#7]
Hello, maybe bevy_pixels shines with pixel collision with twisted shapes ?
if possible, could you show this with a dragon curve shape or a fractal snowflake ?

**Comment by dtcristo** [comment]
I'm not sure what you're asking for here? Some kind of example?

I don't think pixel collision would be something _this_ library would handle, as here we're just integrating the [pixels](https://github.com/parasyte/pixels) renderer into a bevy application. It's quite simple.

**Comment by pyweeker** [comment]
hello, usually sprites are squares, maybe with alpha on edges, but the collision checker works on squares.
if you have big shapes like this which collide [https://stickeramoi.com/9556/sticker-etoile-de-mer.jpg](https://stickeramoi.com/9556/sticker-etoile-de-mer.jpg)
it is processed as square collisions, which is wrong.

**Comment by dtcristo** [comment]
Yeah that makes sense. However, that's not really what `bevy_pixels` is used for. It's just a library to allow you to render a framebuffer to the screen using [`pixels`](https://github.com/parasyte/pixels) where you write raw pixel data yourself. It has nothing to do with sprites or collisions. Seems like this capability should be part of `bevy` itself or a separate library.
